# Generated by Django 3.0.3 on 2021-05-18 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20210203_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='click_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
