# Generated by Django 3.0.3 on 2021-05-18 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_objectviewed_click_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='click_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
