# Generated by Django 3.0.3 on 2021-05-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20210518_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectviewed',
            name='click_id',
        ),
    ]
