# Generated by Django 3.0.3 on 2021-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20210520_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.UUIDField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
