# Generated by Django 3.0.3 on 2021-05-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20210520_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueId',
        ),
    ]
