# Generated by Django 3.0.3 on 2021-02-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigntopublisher',
            old_name='status',
            new_name='status_cam',
        ),
    ]
