# Generated by Django 3.0.3 on 2021-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaign', '0002_auto_20210202_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='publisher_campaign',
            field=models.ManyToManyField(related_name='publisher_camp', through='campaign.CampaignToPublisher', to='accounts.Publisher'),
        ),
    ]
