# Generated by Django 3.0.3 on 2021-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210209_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntopublisher',
            name='pixel',
            field=models.URLField(blank=True, null=True, verbose_name='Pigyback Pixel/URL'),
        ),
    ]
