# Generated by Django 3.0.3 on 2021-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaigntopublisher_pixel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('declined', 'Declined')], help_text='Choose the campaing status', max_length=22, verbose_name='Status'),
        ),
    ]
