# Generated by Django 3.0.3 on 2021-02-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(max_length=235)),
                ('campaign_id', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('publisher_id', models.PositiveIntegerField()),
                ('click_timestamp', models.DateTimeField()),
                ('lead_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Object Lead',
                'verbose_name_plural': 'Objects Lead',
                'ordering': ['-lead_timestamp'],
            },
        ),
    ]
