# Generated by Django 3.0.3 on 2021-02-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_objectlead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectlead',
            name='click_timestamp',
        ),
    ]
