# Generated by Django 3.0.3 on 2021-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20210203_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlead',
            name='ip_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
