# Generated by Django 3.0.3 on 2021-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_objectviewed_click_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='click_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
