# Generated by Django 3.0.3 on 2021-02-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Enter the company/brand name', max_length=150, verbose_name='Company Name')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Enter mail id', max_length=300, verbose_name='Mail ID')),
                ('advertiser_category', models.CharField(choices=[('Affiliate', 'Affiliate'), ('Affiliate_Network', 'Affiliate Network'), ('Branding', 'Branding'), ('Direct', 'Direct'), ('Lead_Generation', 'Lead Generation'), ('Arbitrage', 'Arbitrage')], help_text='Which category best describes the primary offers you will be advertising?', max_length=22, verbose_name='Advertiser Category')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('declined', 'Declined')], help_text='Choose the advertiser status', max_length=22, verbose_name='Status')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_agency', to='agency.Agency')),
            ],
        ),
    ]
