# Generated by Django 3.0.3 on 2021-05-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20210526_1134'),
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_category',
            field=models.CharField(choices=[('Affiliate', 'Affiliate'), ('Affiliate_Network', 'Affiliate Network'), ('Branding', 'Branding'), ('Direct', 'Direct'), ('Lead_Generation', 'Lead Generation'), ('Arbitrage', 'Arbitrage')], help_text='Which category best describes the primary offers you will be advertising?', max_length=22, verbose_name='Advertiser Category *'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Select agency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_agency', to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='company_name',
            field=models.CharField(help_text='Enter the company/brand name', max_length=150, verbose_name='Company Name *'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(help_text='Enter mail id', max_length=300, verbose_name='Mail ID *'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name *'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name *'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('declined', 'Declined')], help_text='Choose the advertiser status', max_length=22, verbose_name='Status *'),
        ),
    ]
