# Generated by Django 3.0.3 on 2021-05-26 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='alternate_number',
            field=models.BigIntegerField(blank=True, help_text="Enter the agency's alternate number", null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Alternate Contact Number'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contact_number',
            field=models.BigIntegerField(help_text="Enter the agency's contact number", validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name="Agency's Contact Number"),
        ),
    ]
