# Generated by Django 3.0.3 on 2021-05-26 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20210526_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_address',
            field=models.CharField(help_text="Enter the agency's address/city", max_length=300, verbose_name="Agency's Address/City *"),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(help_text='Enter the agency name', max_length=200, verbose_name='Agency Name *'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contact_number',
            field=models.BigIntegerField(help_text="Enter the agency's contact number", validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name="Agency's Contact Number *"),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contact_person',
            field=models.CharField(help_text="Enter the agency's contact person's name", max_length=150, verbose_name="Contact Person's Name *"),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(help_text="Enter the agency/contact person's mail id", max_length=400, verbose_name="Agency/Contact Person's Mail ID *"),
        ),
    ]
